# Generated by Django 5.1.6 on 2025-05-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=6)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('SENT', 'SENT')], max_length=10)),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webhook.conversation')),
            ],
        ),
    ]
